---
- hosts: localhost
  gather_facts: no
  vars_prompt:
  - name: target_host
    prompt: please enter the target host IP
    private: no
  tasks:
    - add_host:
        name: "{{ item }}"
        groups: dynamically_created_hosts
      with_items: "{{ target_host.split(',') }}"


- hosts: dynamically_created_hosts
  tasks:
  - debug: msg="do things on target host here"

tasks:

- name: Enable EPEL Repository on CentOS 8
dnf:
name: epel-release
state: latest
become: True
when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '8'

- name: Enable EPEL Repository on CentOS 7
yum:
name: epel-release
state: latest
become: True
when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7'
